### Packages#####
library(here)
source(here("source", "libraries.R"))
library(phyloseq)
library(viridis)
library(metacoder)
library(dplyr)
library(ggpp)
library(mctoolsr)

#### Data ####

load(here("Rdata","ps_obj.RData"))

ps_rhizo <-  subset_samples(ps, Sample.type =="Rhizosphere")
ps_rhizo <- prune_taxa(taxa_sums(ps_rhizo)>0, ps_rhizo)
ps_rhizo
# 81 samples 5954 taxa

sample_names(ps_rhizo) <- sub("Meso.*","",sample_names(ps_rhizo))

###______#####
### BETA DIV ####

####__ Robust Aitchison ####
ps_rclr <- microbiome::transform(ps_rhizo, "rclr") # Robust Aitchison transformation

## Sanity check ###
# Does it give the same transformation than vegan?
ASV_phylo_rclr <- data.frame(otu_table(ps_rclr))

ASV <- t(data.frame(otu_table(ps_rhizo))) # Columns as species !
ASV_vegan_rclr <- decostand(x = ASV,method="rclr")
ASV_vegan_rclr <- data.frame(t(ASV_vegan_rclr))# put it back into species as rows

identical(ASV_phylo_rclr,ASV_vegan_rclr) # should be true 

### Permanova 
rclr_dist_matrix <- phyloseq::distance(ps_rclr, method = "euclidean") # Aitchison distance
metadata <- as(sample_data(ps_rclr), "data.frame") # Export data

Permanova.rclr<-adonis2(rclr_dist_matrix~Plant.type*Time*Temperature,
                        data = metadata,
                        permutations = 999)

# Save Permanova resutls in csv file
write.table(Permanova.rclr,row.names=T,sep=";",here("Results","Tables","Rhizo_RCLR_Permanova.csv"))

# Code if you want your table as a gg object
# Permanova_table <- as.data.frame(Permanova.rclr)
# Permanova_table[,c(2:4)] <- round(Permanova_table[,c(2:4)],2)
# table.p <- ggtexttable(Permanova_table, rows = NULL)

#### Ordinations 
ord_rclr <- phyloseq::ordinate(ps_rclr, "RDA", distance = "euclidean")

## Plant type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[1],3))))

RCLR_ord_plant <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type effect ",subtitle = 'Robust Aitchison distance')+
  scale_shape_manual(values=c(0,5),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_rclr)$Plant.type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_plant$layers <- RCLR_ord_plant$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_plant

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[2],3))))

RCLR_ord_time <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Time effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[3],3))))

RCLR_ord_temp <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Temperature effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_temp


### Plant type * Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[5],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[5],3))))

RCLR_ord_PTxT <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Plant.type",color="Temperature") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type * Temperature effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,aes(fill=sample_data(ps_rclr)$Temperature))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(22,23),name="Plant type")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  scale_color_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  # Add both color and fill to get the desired graphical output
# If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_PTxT$layers<- RCLR_ord_PTxT$layers[-1] 


ggarrange(RCLR_ord_plant,RCLR_ord_temp,RCLR_ord_time,RCLR_ord_PTxT,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","Rhizo_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","Rhizo_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)
  
### pairwise permanova
calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Time",999) 

#####__ Hellinger distance #####
### Permanova 
ps_hell <- microbiome::transform(ps_rhizo, "hellinger")    

hell_dist_matrix <- phyloseq::distance(ps_hell, method = "euclidean") # Hellinger distance
metadata <- as(sample_data(ps_hell), "data.frame") # Export data

Permanova.hell<-adonis2(hell_dist_matrix~Plant.type*Time*Temperature,
                        data = metadata,
                        permutations = 999)

write.table(Permanova.hell,row.names=T,sep=";",here("Results","Tables","Rhizo_Hellinger_Permanova.csv"))

## Ordination ##
ord_hell <- phyloseq::ordinate(ps_hell, "RDA", distance = "euclidean")

## Plant type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[1],3))))

Hell_ord_plant <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type effect ",subtitle = 'Hellinger distance')+
  scale_shape_manual(values=c(0,5),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_hell)$Plant.type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

Hell_ord_plant$layers <- Hell_ord_plant$layers[-1] # removes the original points generated by plot_ordination
Hell_ord_plant

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[2],3))))

Hell_ord_time <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Time effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
Hell_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[3],3))))

Hell_ord_temp <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Temperature effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
Hell_ord_temp


### Plant type * Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[5],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[5],3))))

Hell_ord_PTxT <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Plant.type",color="Temperature") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type * Temperature effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,aes(fill=sample_data(ps_hell)$Temperature))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(22,23),name="Plant type")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  scale_color_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  # Add both color and fill to get the desired graphical output
  # If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

Hell_ord_PTxT$layers<- Hell_ord_PTxT$layers[-1] 


ggarrange(Hell_ord_plant,Hell_ord_temp,Hell_ord_time,Hell_ord_PTxT,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","Rhizo_Hell_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","Rhizo_Hell_Ordination.pdf"),device='png',height = 7.5, width = 10.5)




#####__ Bray_curtis distance #####
### Permanova 

bc_dist_matrix <- phyloseq::distance(ps_rhizo, method = "bray") # Bray_Curtis distance
metadata <- as(sample_data(ps_rhizo), "data.frame") # Export data

Permanova.bc<-adonis2(bc_dist_matrix~Plant.type*Time*Temperature,
                        data = metadata,
                        permutations = 999)

write.table(Permanova.bc,row.names=T,sep=";",here("Results","Tables","Rhizo_Bray_Curtis_Permanova.csv"))

## Ordination ##
ord_bc <- phyloseq::ordinate(ps_rhizo, "RDA", distance = "bray")


## Plant type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[1],3))))

BC_ord_plant <- phyloseq::plot_ordination(ps_rhizo, ord_bc, type="samples",shape="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type effect ",subtitle = 'Bray_Curtis distance')+
  geom_text(aes(label = sample_names(ps_rhizo)), size = 3.5)+
  scale_shape_manual(values=c(0,5),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_rhizo)$Plant.type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_plant$layers <- BC_ord_plant$layers[-1] # removes the original points generated by plot_ordination
BC_ord_plant

## Sample 3 is an outlier

ASVRhizo <- data.frame(otu_table(ps_rhizo))
colSums(ASVRhizo)
mean(colSums(ASVRhizo))
#Sample 3 has 38990 reads, very close to the mean.. 
# So the difference must be due to ASVs being specific to that sample 

ASV_S3 <- subset(ASVRhizo,ASVRhizo[,c('X3')]>0)
# One ASV has 14633 reads 14633
ASV_interest <- subset(ASV_S3,ASV_S3[,c('X3')]==14633)

TAX_S3 <- data.frame(tax_table(ps_rhizo))
TAX_S3 <- subset(TAX_S3,rownames(TAX_S3)%in%rownames(ASV_interest))
# ASV labelled as Flavobacterium sp

#### Removing ASV #####
ps_rhizo_noflavo <- prune_taxa(taxa_names(ps_rhizo)!=rownames(ASV_interest), ps_rhizo)

bc_dist_matrix <- phyloseq::distance(ps_rhizo_noflavo, method = "bray") # Bray_Curtis distance
metadata <- as(sample_data(ps_rhizo_noflavo), "data.frame") # Export data

Permanova.bc<-adonis2(bc_dist_matrix~Plant.type*Time*Temperature,
                      data = metadata,
                      permutations = 999)

write.table(Permanova.bc,row.names=T,sep=";",here("Results","Tables","Rhizo_Bray_Curtis_Permanova.csv"))

## Ordination ##
ord_bc <- phyloseq::ordinate(ps_rhizo_noflavo, "RDA", distance = "bray")


## Plant type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[1],3))))

BC_ord_plant <- phyloseq::plot_ordination(ps_rhizo_noflavo, ord_bc, type="samples",shape="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type effect ",subtitle = 'Bray_Curtis distance')+
  #geom_text(aes(label = sample_names(ps_rhizo_noflavo)), size = 3.5)+
  scale_shape_manual(values=c(0,5),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_rhizo)$Plant.type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_plant$layers <- BC_ord_plant$layers[-1] # removes the original points generated by plot_ordination
BC_ord_plant

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[2],3))))

BC_ord_time <- phyloseq::plot_ordination(ps_rhizo_noflavo, ord_bc, type="samples") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Time effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rhizo_noflavo)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
BC_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[3],3))))

BC_ord_temp <- phyloseq::plot_ordination(ps_rhizo, ord_bc, type="samples") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Temperature effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rhizo)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
BC_ord_temp


### Plant type * Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[5],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[5],3))))

BC_ord_PTxT <- phyloseq::plot_ordination(ps_rhizo, ord_bc, type="samples",shape="Plant.type",color="Temperature") + 
  theme_bw()+
  ggtitle(label = "Rhizosphere - Plant type * Temperature effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,aes(fill=sample_data(ps_rhizo)$Temperature))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(22,23),name="Plant type")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  scale_color_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  # Add both color and fill to get the desired graphical output
  # If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_PTxT$layers<- BC_ord_PTxT$layers[-1] 


ggarrange(BC_ord_plant,BC_ord_temp,BC_ord_time,BC_ord_PTxT,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","Rhizo_BC_ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","Rhizo_BC_ordination.pdf"),device='png',height = 7.5, width = 10.5)


