### Packages#####
library(here)
source(here("source", "libraries.R"))
library(phyloseq)
library(viridis)
library(metacoder)
library(dplyr)
library(ggpp)
library(mctoolsr)

#### Data ####

load(here("Rdata","ps_obj.RData"))

ps_plant <-  subset_samples(ps, Sample.type !="Sediment")
ps_plant <- prune_taxa(taxa_sums(ps_plant)>0, ps_plant)
ps_plant
# 162 samples 6319 taxa

###______#####
### BETA DIV ####

####__ Robust Aitchison ####
ps_rclr <- microbiome::transform(ps_plant, "rclr") # Robust Aitchison transformation

## Sanity check ###
# Does it give the same transformation than vegan?
ASV_phylo_rclr <- data.frame(otu_table(ps_rclr))

ASV <- t(data.frame(otu_table(ps_plant))) # Columns as species !
ASV_vegan_rclr <- decostand(x = ASV,method="rclr")
ASV_vegan_rclr <- data.frame(t(ASV_vegan_rclr))# put it back into species as rows

identical(ASV_phylo_rclr,ASV_vegan_rclr) # should be true 

### Permanova 
rclr_dist_matrix <- phyloseq::distance(ps_rclr, method = "euclidean") # Aitchison distance
metadata <- as(sample_data(ps_rclr), "data.frame") # Export data

Permanova.rclr<-adonis2(rclr_dist_matrix~Sample.type*Plant.type*Time*Temperature,
                        data = metadata,
                        permutations = 999)

# Save Permanova resutls in csv file
write.table(Permanova.rclr,row.names=T,sep=";",here("Results","Tables","RootRhizo_RCLR_Permanova.csv"))

# Code if you want your table as a gg object
# Permanova_table <- as.data.frame(Permanova.rclr)
# Permanova_table[,c(2:4)] <- round(Permanova_table[,c(2:4)],2)
# table.p <- ggtexttable(Permanova_table, rows = NULL)

#### Ordinations 
ord_rclr <- phyloseq::ordinate(ps_rclr, "RDA", distance = "euclidean")

## Sample type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[1],3))))

RCLR_ord_comp <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",color="Sample.type",shape="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Planted - Compartment effect ",subtitle = 'Robust Aitchison distance')+
  #geom_point(aes(shape=sample_data(ps_rclr)$Plant.type),size=4)
  geom_point(size=3)+
  scale_shape_manual(values=c(22,23),name="Plant type")+
  scale_color_manual(values=c("darkgreen","brown"),name="Compartment")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_comp$layers <- RCLR_ord_comp$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_comp


### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[3],3))))

RCLR_ord_time <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Planted - Time effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[4],3))))

RCLR_ord_temp <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Planted - Temperature effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_temp


ggarrange(RCLR_ord_comp,RCLR_ord_temp,RCLR_ord_time,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","RoRh_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","RoRh_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)

