### Packages#####
library(here)
source(here("source", "libraries.R"))
library(phyloseq)
library(viridis)
library(metacoder)
library(dplyr)
library(ggpp)
library(pairwiseAdonis)

#### Data ####

load(here("Rdata","ps_obj.RData"))

ps_sed <-  subset_samples(ps, Sample.type =="Sediment")
ps_sed <- prune_taxa(taxa_sums(ps_sed)>0, ps_sed)
ps_sed
# 120 samples 18851 taxa

# Simplify sample names 
sample_names(ps_sed) <- sub("Meso.*","",sample_names(ps_sed))


###______#####
### BETA DIV ####

#### Robust Aitchison ####
ps_rclr <- microbiome::transform(ps_sed, "rclr") # Robust Aitchison transformation

## Sanity check ###
# Does it give the same transformation than vegan?
ASV_phylo_rclr <- data.frame(otu_table(ps_rclr))

ASV <- t(data.frame(otu_table(ps_sed))) # Columns as species !
ASV_vegan_rclr <- decostand(x = ASV,method="rclr")
ASV_vegan_rclr <- data.frame(t(ASV_vegan_rclr))# put it back into species as rows

identical(ASV_phylo_rclr,ASV_vegan_rclr) # Should be true 

### Permanova 
rclr_dist_matrix <- phyloseq::distance(ps_rclr, method = "euclidean") # Robust Aitchison distance
metadata <- as(sample_data(ps_rclr), "data.frame") # Metadata

Permanova.rclr<-adonis2(rclr_dist_matrix~Plant.type*Time*Temperature,
                        data = metadata,
                        permutations = 999)

# Save Permanova results in csv file
write.table(Permanova.rclr,row.names=T,sep=";",here("Results","Tables","Sed_RCLR_Permanova.csv"))



#### PCA plots  
ord_rclr <- phyloseq::ordinate(ps_rclr, "RDA", distance = "euclidean")

## Plant type  

# Code to annotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[1],3))))

## 
RCLR_ord_plant <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Plant.type",color="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Sediments - Robust Aitchison distance")+
  scale_shape_manual(values=c(1,0,5),name="Plant type")+
  scale_colour_manual(values = c("chocolate", "slateblue4","chartreuse4"),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_clr)$Plant.type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_plant$layers <- RCLR_ord_plant$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_plant


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[3],3))))

RCLR_ord_temp <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Sediments - Robust Aitchison distance")+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_clr)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_temp


### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[2],3))))

RCLR_ord_time <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Sediments - Robust Aitchison distance")+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_clr)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_time

### Save figure 
ggarrange(RCLR_ord_plant,RCLR_ord_temp,RCLR_ord_time,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","Sed_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","Sed_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)


# Time x Plant type #
RCLR_fig<- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape='Plant.type',color='Time') + 
  theme_bw()+
  ggtitle(label = "Sediments - Robust Aitchison distance")+
  geom_point(size=4,aes(fill=sample_data(ps_clr)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Plant type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+ # Add both color and fill to get the desired graphical output
  scale_colour_viridis(option="magma",discrete=T,name="Time")
# Add both color and fill to get the desired graphical output
# If only fill -> legend is black.. All this because plot_ordination does not have a fill option
RCLR_fig$layers <- RCLR_fig$layers[-1] 
RCLR_fig



###### Interactions - Pairwise permanova #####

metadata$Temperature <- sub("10°C day 5°C night","Cold",metadata$Temperature)
metadata$Temperature <- sub("20°C day 10°C night","Warm",metadata$Temperature)

metadata$plant_temp = paste0(metadata$Plant.type, "_", metadata$Temperature)
metadata$time_temp = paste0(metadata$Time, "_", metadata$Temperature)
metadata$plant_time = paste0(metadata$Plant.type, "_", metadata$Time)

# Characters to factor
metadata[sapply(metadata, is.character)] <- lapply(metadata[sapply(metadata, is.character)], as.factor) # did it work? Check with str(meta)
str(metadata)

# Plant x Temperature 
Permanova.plant_temp <- adonis2(rclr_dist_matrix~plant_temp,
                                data = metadata, permutations = 999)
Permanova.plant_temp

Pairwise.plant_temp <- pairwise.adonis(rclr_dist_matrix, metadata$plant_temp,p.adjust.m ="bonferroni")
Pairwise.plant_temp
write.table(Pairwise.plant_temp,row.names=T,sep=";",here("Results/Tables/Interactions","Sed_RCLR_PWP_Plant_Temp.csv"))


# Time x Temperature 
Permanova.time_temp <- adonis2(rclr_dist_matrix~time_temp,
                               data = metadata, permutations = 999)
Permanova.time_temp

Pairwise.time_temp <- pairwise.adonis(rclr_dist_matrix, metadata$time_temp,p.adjust.m ="bonferroni")
Pairwise.time_temp
write.table(Pairwise.time_temp,row.names=T,sep=";",here("Results/Tables/Interactions","Sed_RCLR_PWP_Time_Temp.csv"))

# Plant x Time 
Permanova.plant_time <- adonis2(rclr_dist_matrix~plant_time,
                                data = metadata, permutations = 999)
Permanova.plant_time

Pairwise.plant_time <- pairwise.adonis(rclr_dist_matrix, metadata$plant_time,p.adjust.m ="bonferroni")
Pairwise.plant_time
write.table(Pairwise.plant_time,row.names=T,sep=";",here("Results/Tables/Interactions","Sed_RCLR_PWP_Time_Plant.csv"))

#_______________________________#
#_______________________________#
#_______________________________#

# Open the csv files and remove lines with un-relevant pairwise comparisons
# remove padjusted and sig column 
# Save file example "Sed_Relevant_PlantxTemp_Comp.csv" in the Interactions folder


##### Relevant pairwise permanovas #####

# Load file with the relevant pairwise comparisons

# Plant Type x Temperature 
Pairwise_relevant_PTxTemp <- read.csv(file = here("Results/Tables/Interactions","Sed_Relevant_PlantxTemp_Comp.csv"), 
                             dec = ".", sep = ";", header = T, row.names = 1, comment.char = "")


Pairwise_relevant_PTxTemp$p.adj.FDR <- p.adjust(Pairwise_relevant_PTxTemp$p.value,method="fdr" )
Pairwise_relevant_PTxTemp$p.adj.Bon <- p.adjust(Pairwise_relevant_PTxTemp$p.value,method="bonferroni" )

write.table(Pairwise_relevant_PTxTemp,row.names=T,sep=";",here("Results","Tables","Sed_RCLR_relevant_PWP_PTxTemp.csv"))


# Plant Type x Time
Pairwise_relevant_PTxTime <- read.csv(file = here("Results/Tables/Interactions","Sed_Relevant_PlantxTime_Comp.csv"), 
                                      dec = ".", sep = ";", header = T, row.names = 1, comment.char = "")


Pairwise_relevant_PTxTime$p.adj.FDR <- p.adjust(Pairwise_relevant_PTxTime$p.value,method="fdr" )
Pairwise_relevant_PTxTime$p.adj.Bon <- p.adjust(Pairwise_relevant_PTxTime$p.value,method="bonferroni" )

write.table(Pairwise_relevant_PTxTime,row.names=T,sep=";",here("Results","Tables","Sed_RCLR_relevant_PWP_PTxTime.csv"))

# NOT REALLY RELEVANT 
# Time x Temperature 
# Pairwise_relevant_TimexTemp <- read.csv(file = here("Results/Tables/Interactions","Sed_Relevant_PlantxTemp_Comp.csv"), 
#                                       dec = ".", sep = ";", header = T, row.names = 1, comment.char = "")
# 
# 
# Pairwise_relevant_TimexTemp$p.adj.FDR <- p.adjust(Pairwise_relevant_TimexTemp$p.value,method="fdr" )
# Pairwise_relevant_TimexTemp$p.adj.Bon <- p.adjust(Pairwise_relevant_TimexTemp$p.value,method="bonferroni" )
# 
# write.table(Pairwise_relevant_TimexTemp,row.names=T,sep=";",here("Results","Tables","Sed_RCLR_relevant_PWP_TimexTemp.csv"))










####Hellinger distance #####
### Permanova 
ps_hell <- microbiome::transform(ps_sed, "hellinger")    

hell_dist_matrix <- phyloseq::distance(ps_hell, method = "euclidean") # Hellinger distance
metadata <- as(sample_data(ps_hell), "data.frame") # Export data

Permanova.hell<-adonis2(hell_dist_matrix~Plant.type*Time*Temperature,
                        data = metadata,
                        permutations = 999)

write.table(Permanova.hell,row.names=T,sep=";",here("Results","Tables","Sed_Hellinger_Permanova.csv"))

## PCA plots
ord_hell <- phyloseq::ordinate(ps_hell, "RDA", distance = "euclidean")


## Plant type  
hell_ord_plant <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Plant.type",color="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Sediments - Hellinger distance")+
  scale_shape_manual(values=c(1,0,5),name="Plant type")+
  scale_colour_manual(values = c("chocolate", "slateblue4","chartreuse4"),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_hell)$Plant.type),size=4)


hell_ord_plant$layers <- hell_ord_plant$layers[-1] # removes the original points generated by plot_ordination
hell_ord_plant

### Temperature
hell_ord_temp <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Sediments - Hellinger distance")+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")
hell_ord_temp

#### Time 

hell_ord_time <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Sediments - Hellinger distance")+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")
hell_ord_time


ggarrange(hell_ord_plant,hell_ord_temp,hell_ord_time,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","Sed_Hellinger_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)




#### Bray-Curtis ####  
BC_dist_matrix <- phyloseq::distance(ps_sed, method = "bray") # Bray_curtis distance
metadata <- as(sample_data(ps_sed), "data.frame") # Export data

Permanova.BC<-adonis2(BC_dist_matrix~Plant.type*Time*Temperature,
                      data = metadata,
                      permutations = 999)

write.table(Permanova.BC,row.names=T,sep=";",here("Results","Tables","Sed_BrayCurtis_Permanova.csv"))

head(BC_dist_matrix)


## PCoA plots ##
ord_bray <- phyloseq::ordinate(ps_sed, "PCoA", distance = "bray")


## Plant type  
BC_ord_plant <- phyloseq::plot_ordination(ps_sed, ord_bray, type="samples",shape="Plant.type",color="Plant.type") + 
  theme_bw()+
  ggtitle(label = "Sediments - Bray-Curtis distance")+
  scale_shape_manual(values=c(1,0,5),name="Plant type")+
  scale_colour_manual(values = c("chocolate", "slateblue4","chartreuse4"),name="Plant type")+
  geom_point(aes(shape=sample_data(ps_sed)$Plant.type),size=4) 

BC_ord_plant$layers <- BC_ord_plant$layers[-1] # removes the original points generated by plot_ordination
BC_ord_plant

### Temperature
BC_ord_temp <- phyloseq::plot_ordination(ps_sed, ord_bray, type="samples") + 
  theme_bw()+
  ggtitle(label = "Sediments - Bray-Curtis distance")+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_sed)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")
BC_ord_temp

#### Time 
BC_ord_time <- phyloseq::plot_ordination(ps_sed, ord_bray, type="samples") + 
  theme_bw()+
  ggtitle(label = "Sediments - Bray-Curtis distance")+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_sed)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")
BC_ord_time


ggarrange(BC_ord_plant,BC_ord_temp,BC_ord_time,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","Sed_Bray_Curtis_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)

#### ____ #####
#### Pairwise permanova #####
calc_pairwise_permanovas(BC_dist_matrix, metadata,"Time",999) 
calc_pairwise_permanovas(hell_dist_matrix, metadata,"Time",999) 
calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Time",999)
calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Plant.type",999)

# For all 3 distances used, D62 communities are always significantly different from the rest

