### Packages#####
library(here)
source(here("source", "libraries.R"))
library(phyloseq)
library(viridis)
library(metacoder)
library(dplyr)
library(ggpp)
library(mctoolsr)
library(microbiome)
#### Data ####

load(here("Rdata","ps_18S_water_obj.RData"))

###______#####
### BETA DIV ####

##### Robust Aitchison ####
ps_rclr <- microbiome::transform(ps, "rclr") # Robust Aitchison transformation

## Sanity check ###
# Does it give the same transformation than vegan?
ASV_phylo_rclr <- data.frame(otu_table(ps_rclr))

ASV <- t(data.frame(otu_table(ps))) # Columns as species !
ASV_vegan_rclr <- decostand(x = ASV,method="rclr")
ASV_vegan_rclr <- data.frame(t(ASV_vegan_rclr))# put it back into species as rows

identical(ASV_phylo_rclr,ASV_vegan_rclr) # should be true 

### Permanova 
rclr_dist_matrix <- phyloseq::distance(ps_rclr, method = "euclidean") # Aitchison distance
metadata <- as(sample_data(ps_rclr), "data.frame") # Export data

Permanova.rclr<-adonis2(rclr_dist_matrix~Time*Sample_type*Temperature,
                        data = metadata,
                        permutations = 999)
Permanova.rclr


# Save Permanova resutls in csv file
write.table(Permanova.rclr,row.names=T,sep=";",here("Results","Tables","18S_Water_RCLR_Permanova.csv"))

# Code if you want your table as a gg object
# Permanova_table <- as.data.frame(Permanova.rclr)
# Permanova_table[,c(2:4)] <- round(Permanova_table[,c(2:4)],2)
# table.p <- ggtexttable(Permanova_table, rows = NULL)

#### PCA 
ord_rclr <- phyloseq::ordinate(ps_rclr, "RDA", distance = "euclidean")

## Sample type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[2],3))))

RCLR_ord_stype <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Sample_type") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type effect ",subtitle = 'Robust Aitchison distance')+
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  geom_point(aes(shape=sample_data(ps_rclr)$Sample_type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "left", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_stype$layers <- RCLR_ord_stype$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_stype

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[1],3))))

RCLR_ord_time <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Time effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "left", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[3],3))))

RCLR_ord_temp <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Temperature effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "left", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_temp


### Sample type * Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[4],3))))

RCLR_ord_STxTime <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Sample_type",color="Time") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type * Time effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,aes(fill=sample_data(ps_rclr)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  scale_color_viridis(option="magma",discrete=T,name="Time")+
  # Add both color and fill to get the desired graphical output
# If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "left", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_STxTime$layers<- RCLR_ord_STxTime$layers[-1] 


ggarrange(RCLR_ord_stype,RCLR_ord_temp,RCLR_ord_time,RCLR_ord_STxTime,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","18S_Water_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","18S_Water_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)
  
#### Pairwise permanova ###
calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Time",999) 
calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Sample_type",999) 


#####Hellinger distance #####
### Permanova 
ps_hell <- microbiome::transform(ps, "hellinger")    

hell_dist_matrix <- phyloseq::distance(ps_hell, method = "euclidean") # Hellinger distance
metadata <- as(sample_data(ps_hell), "data.frame") # Export data

Permanova.hell<-adonis2(hell_dist_matrix~Time*Sample_type*Temperature,
                        data = metadata,
                        permutations = 999)
Permanova.hell


write.table(Permanova.hell,row.names=T,sep=";",here("Results","Tables","18S_Water_Hellinger_Permanova.csv"))

## PCA ##
ord_hell <- phyloseq::ordinate(ps_hell, "RDA", distance = "euclidean")

## Sample type  

# Allows to nicely annotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[2],3))))

Hell_ord_stype <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Sample_type") + 
  theme_bw()+
  ggtitle(label = "Water - sample type effect ",subtitle = 'Hellinger distance')+
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  geom_point(aes(shape=sample_data(ps_hell)$Sample_type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

Hell_ord_stype$layers <- Hell_ord_stype$layers[-1] # removes the original points generated by plot_ordination
Hell_ord_stype

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[1],3))))

Hell_ord_time <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Time effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
Hell_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[3],3))))

Hell_ord_temp <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Temperature effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
Hell_ord_temp


### Sample type * Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[4],3))))

Hell_ord_STxTime <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Sample_type",color="Time") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type * Time effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,aes(fill=sample_data(ps_hell)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  scale_color_viridis(option="magma",discrete=T,name="Time")+
  # Add both color and fill to get the desired graphical output
  # If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

Hell_ord_STxTime$layers<- Hell_ord_STxTime$layers[-1] 


ggarrange(Hell_ord_stype,Hell_ord_temp,Hell_ord_time,Hell_ord_STxTime,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","18S_Water_Hell_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","18S_Water_Hell_Ordination.png"),device='png',height = 7.5, width = 10.5)




#####Bray_curtis distance #####
### Permanova 

bc_dist_matrix <- phyloseq::distance(ps, method = "bray") # Bray_Curtis distance
metadata <- as(sample_data(ps), "data.frame") # Export data

Permanova.bc<-adonis2(bc_dist_matrix~Time*Sample_type*Temperature,
                        data = metadata,
                        permutations = 999)
Permanova.bc


write.table(Permanova.bc,row.names=T,sep=";",here("Results","Tables","18S_Water_Bray_Curtis_Permanova.csv"))

## PCoA ##
ord_bc <- phyloseq::ordinate(ps, "PCoA", distance = "bray")


## Sample type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[2],3))))

BC_ord_stype <- phyloseq::plot_ordination(ps, ord_bc, type="samples",shape="Sample_type") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type effect ",subtitle = 'Bray_Curtis distance')+
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  geom_point(aes(shape=sample_data(ps)$Sample_type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_stype$layers <- BC_ord_stype$layers[-1] # removes the original points generated by plot_ordination
BC_ord_stype


### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[1],3))))

BC_ord_time <- phyloseq::plot_ordination(ps, ord_bc, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Time effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
BC_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[3],3))))

BC_ord_temp <- phyloseq::plot_ordination(ps, ord_bc, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Temperature effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
BC_ord_temp


### Sample type * Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[4],3))))

BC_ord_STxTime <- phyloseq::plot_ordination(ps, ord_bc, type="samples",shape="Sample_type",color="Time") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type * Time effect ",subtitle = 'Bray Curtis distance')+
  geom_point(size=4,aes(fill=sample_data(ps)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  scale_color_viridis(option="magma",discrete=T,name="Time")+
  # Add both color and fill to get the desired graphical output
  # If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_STxTime$layers<- BC_ord_STxTime$layers[-1] 


ggarrange(BC_ord_stype,BC_ord_temp,BC_ord_time,BC_ord_STxTime,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","18S_Water_BC_ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","18S_Water_BC_ordination.png"),device='png',height = 7.5, width = 10.5)


