### Packages#####
library(here)
source(here("source", "libraries.R"))
library(phyloseq)
library(viridis)
library(metacoder)
library(dplyr)
library(ggpp)
library(mctoolsr)
library(pairwiseAdonis)
library(microbiome)
#### Data ####

load(here("Rdata","ps_16S_water_obj.RData"))

#### Separation by temperature #####

ps_water_16S_Warm <- subset_samples(ps, Temperature =="20C day - 10C night")
ps_water_16S_Warm <- prune_taxa(taxa_sums(ps_water_16S_Warm)>0, ps_water_16S_Warm)
ps_water_16S_Warm # 68 samples - 2208 taxa
# check to see if you kept only water_16S samples in WARM condition
str(sample_data(ps_water_16S_Warm)) 

ps_water_16S_Cold <- subset_samples(ps, Temperature =="10C day - 5C night")
ps_water_16S_Cold <- prune_taxa(taxa_sums(ps_water_16S_Cold)>0, ps_water_16S_Cold)
ps_water_16S_Cold # 71 samples - 2019 taxa
# check to see if you kept only water_16S samples in COLD condition
str(sample_data(ps_water_16S_Cold)) 


### BETA DIV ####
#### Robust Aitchison ####
#### | WARM ####
ps_Warm_rclr <- microbiome::transform(ps_water_16S_Warm, "rclr") # Robust Aitchison transformation

##### Permanova ####
rclr_dist_matrix <- phyloseq::distance(ps_Warm_rclr, method = "euclidean") # Robust Aitchison distance
metadata <- as(sample_data(ps_Warm_rclr), "data.frame") # Metadata

Permanova.Warm.rclr<-adonis2(rclr_dist_matrix~Sample_type*Time,
                             data = metadata,
                             permutations = 999)

# Save Permanova results in csv file
write.table(Permanova.Warm.rclr,row.names=T,sep=";",
            here("Results_W&C","Tables","water_16S_Warm_RCLR_Permanova.csv"))



###### Interactions - Pairwise permanova #####

metadata$plant_time = paste0(metadata$Sample_type, "_", metadata$Time)

# Characters to factor
metadata[sapply(metadata, is.character)] <- lapply(metadata[sapply(metadata, is.character)], as.factor) # did it work? Check with str(meta)
str(metadata)


# Plant x Time 
Permanova.plant_time <- adonis2(rclr_dist_matrix~plant_time,
                                data = metadata, permutations = 999)
Permanova.plant_time

Pairwise.plant_time <- pairwise.adonis(rclr_dist_matrix, metadata$plant_time)
Pairwise.plant_time

# Subset the pairwise comparison to only keep the relevant ones 
# ie within the same sampling time how do communities differ between plants

# Use grep to check if the numbers after 'D' are the same
# subset based on the condition (ChatGPT helped me with that one)
Pairwise_relevant_PTxTime <- subset(Pairwise.plant_time, grepl("D([0-9]+)\\s+vs\\s+\\w+_D\\1", pairs))

# D([0-9]+)\\s+vs\\s+\\w+_D\\1 captures the number after the first "D" using D([0-9]+)
# ensures there is space (\\s) and "vs" in between, 
# captures any word characters (w) (e.g., Triglochin or Scirpus),
# and then checks if the captured number (\\1) appears again after the second "D".

# Remove the p adjusted and sig columns
# p was adjusted according to all the comparisons 
# but we just want to adjust it according to the number of relevant comparisons
Pairwise_relevant_PTxTime <- Pairwise_relevant_PTxTime[,!(names(Pairwise_relevant_PTxTime))%in%c("p.adjusted","sig")]

Pairwise_relevant_PTxTime$p.adj.FDR <- p.adjust(Pairwise_relevant_PTxTime$p.value,method="fdr" )
Pairwise_relevant_PTxTime$p.adj.Bon <- p.adjust(Pairwise_relevant_PTxTime$p.value,method="bonferroni" )

write.table(Pairwise_relevant_PTxTime,row.names=T,sep=";",here("Results_W&C","Tables","Water_16S_Warm_RCLR_PWP_PTxTime.csv"))




##### PCA plots #### 
ord_Warm_rclr <- phyloseq::ordinate(ps_Warm_rclr, "RDA", distance = "euclidean")

## Plant type  

# Code to annotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
    label = paste(paste0("~italic(R)^{2} == ", round(Permanova.Warm.rclr$R2[1],3)),"~~",
                  paste0("~italic(p) == ",round(Permanova.Warm.rclr$`Pr(>F)`[1],3))))

## 
RCLR_ord_plant_Warm <- phyloseq::plot_ordination(ps_Warm_rclr, ord_Warm_rclr, type="samples",shape="Sample_type",color="Sample_type") + 
    theme_bw()+
    theme(legend.position = "bottom",
          text = element_text(size =15))+
    #ggtitle(label = "water_16Siments - Robust Aitchison distance")+
    geom_point(aes(shape=sample_data(ps_Warm_rclr)$Sample_type),size=4)+
    scale_shape_manual(name="Plant type :",
                       labels=c("No plant",expression(italic(Scirpus)),expression(italic(Triglochin))),
                       values = c(1,0,5))+
    scale_colour_manual(name="Plant type :",
                        labels=c("No plant",expression(italic(Scirpus)),expression(italic(Triglochin))),
                        values = c("darkred", "slateblue4","chartreuse4"))+
    geom_label_npc(data= df.annotations , 
                   aes(npcx = "right", npcy = "bottom", label = label),
                   parse=T,size=6)

RCLR_ord_plant_Warm$layers <- RCLR_ord_plant_Warm$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_plant_Warm


### Time 
df.annotations <- data.frame(
    label = paste(paste0("~italic(R)^{2} == ", round(Permanova.Warm.rclr$R2[2],3)),"~~",
                  paste0("~italic(p) == ",round(Permanova.Warm.rclr$`Pr(>F)`[2],3))))

RCLR_ord_time_Warm <- phyloseq::plot_ordination(ps_Warm_rclr, ord_Warm_rclr, type="samples") + 
    theme_bw()+
    theme(legend.position = "bottom",
          text = element_text(size =15))+
    #ggtitle(label = "water_16Siments - Robust Aitchison distance")+
    geom_point(size=4,shape=21,aes(fill=sample_data(ps_Warm_rclr)$Time),color="black")+
    scale_fill_viridis(option="magma",discrete=T,name="Time :")+
    geom_label_npc(data= df.annotations , 
                   aes(npcx = "right", npcy = "bottom", label = label),
                   parse=T,size=6)
RCLR_ord_time_Warm

### Save figure 
RCLR_Warm <- ggarrange(RCLR_ord_plant_Warm,RCLR_ord_time_Warm,
                       labels=c("A","B"),
                       font.label = list(size=17,face="bold"),
                       legend = "none")

# ggsave(here("Results_W&C","Figures","water_16S_Warm_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
# ggsave(here("Results_W&C","Figures","water_16S_Warm_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)

##### PW PERMANOVA #####

Pairwise.PT <- pairwise.adonis(rclr_dist_matrix, 
                               metadata$Sample_type,
                               p.adjust.m ="fdr")
Pairwise.PT
# Plant types not significantly different from one another

Pairwise.Time<- pairwise.adonis(rclr_dist_matrix, 
                                metadata$Time,
                                p.adjust.m ="fdr")
Pairwise.Time
# All sampling dates are  significantly different from one another 





#####_____________########
####| COLD ####

ps_Cold_rclr <- microbiome::transform(ps_water_16S_Cold, "rclr") # Robust Aitchison transformation

##### Permanova ####
rclr_dist_matrix <- phyloseq::distance(ps_Cold_rclr, method = "euclidean") # Robust Aitchison distance
metadata <- as(sample_data(ps_Cold_rclr), "data.frame") # Metadata

Permanova.Cold.rclr<-adonis2(rclr_dist_matrix~Sample_type*Time,
                             data = metadata,
                             permutations = 999)

# Save Permanova results in csv file
write.table(Permanova.Cold.rclr,row.names=T,sep=";",
            here("Results_W&C","Tables","water_16S_Cold_RCLR_Permanova.csv"))

###### Interactions - Pairwise permanova #####

metadata$plant_time = paste0(metadata$Sample_type, "_", metadata$Time)

# Characters to factor
metadata[sapply(metadata, is.character)] <- lapply(metadata[sapply(metadata, is.character)], as.factor) # did it work? Check with str(meta)
str(metadata)


# Plant x Time 
Permanova.plant_time <- adonis2(rclr_dist_matrix~plant_time,
                                data = metadata, permutations = 999)
Permanova.plant_time

Pairwise.plant_time <- pairwise.adonis(rclr_dist_matrix, metadata$plant_time)
Pairwise.plant_time

# Subset the pairwise comparison to only keep the relevant ones 
# ie within the same sampling time how do communities differ between plants

# Use grep to check if the numbers after 'D' are the same
# subset based on the condition (ChatGPT helped me with that one)
Pairwise_relevant_PTxTime <- subset(Pairwise.plant_time, grepl("D([0-9]+)\\s+vs\\s+\\w+_D\\1", pairs))

# D([0-9]+)\\s+vs\\s+\\w+_D\\1 captures the number after the first "D" using D([0-9]+)
# ensures there is space (\\s) and "vs" in between, 
# captures any word characters (w) (e.g., Triglochin or Scirpus),
# and then checks if the captured number (\\1) appears again after the second "D".

# Remove the p adjusted and sig columns
# p was adjusted according to all the comparisons 
# but we just want to adjust it according to the number of relevant comparisons
Pairwise_relevant_PTxTime <- Pairwise_relevant_PTxTime[,!(names(Pairwise_relevant_PTxTime))%in%c("p.adjusted","sig")]

Pairwise_relevant_PTxTime$p.adj.FDR <- p.adjust(Pairwise_relevant_PTxTime$p.value,method="fdr" )
Pairwise_relevant_PTxTime$p.adj.Bon <- p.adjust(Pairwise_relevant_PTxTime$p.value,method="bonferroni" )

write.table(Pairwise_relevant_PTxTime,row.names=T,sep=";",here("Results_W&C","Tables","Water_16S_Cold_RCLR_PWP_PTxTime.csv"))



##### PCA plots ####  
ord_Cold_rclr <- phyloseq::ordinate(ps_Cold_rclr, "RDA", distance = "euclidean")

## Plant type  

# Code to annotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
    label = paste(paste0("~italic(R)^{2} == ", round(Permanova.Cold.rclr$R2[1],3)),"~~",
                  paste0("~italic(p) == ",round(Permanova.Cold.rclr$`Pr(>F)`[1],3))))

## 
RCLR_ord_plant_Cold <- phyloseq::plot_ordination(ps_Cold_rclr, ord_Cold_rclr, type="samples",shape="Sample_type",color="Sample_type") + 
    theme_bw()+
    theme(legend.position = "bottom",
          text = element_text(size =15))+
    #ggtitle(label = "water_16Siments - Robust Aitchison distance")+
    geom_point(aes(shape=sample_data(ps_Cold_rclr)$Sample_type),size=4)+
    scale_shape_manual(name="Plant type :",
                       labels=c("No plant",expression(italic(Scirpus)),expression(italic(Triglochin))),
                       values = c(1,0,5))+
    scale_colour_manual(name="Plant type :",
                        labels=c("No plant",expression(italic(Scirpus)),expression(italic(Triglochin))),
                        values = c("darkred", "slateblue4","chartreuse4"))+
    geom_label_npc(data= df.annotations , 
                   aes(npcx = "right", npcy = "bottom", label = label),
                   parse=T,size=6)

RCLR_ord_plant_Cold$layers <- RCLR_ord_plant_Cold$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_plant_Cold


### Time 
df.annotations <- data.frame(
    label = paste(paste0("~italic(R)^{2} == ", round(Permanova.Cold.rclr$R2[2],3)),"~~",
                  paste0("~italic(p) == ",round(Permanova.Cold.rclr$`Pr(>F)`[2],3))))

RCLR_ord_time_Cold <- phyloseq::plot_ordination(ps_Cold_rclr, ord_Cold_rclr, type="samples") + 
    theme_bw()+
    theme(legend.position = "bottom",
          text = element_text(size =15))+
    #ggtitle(label = "water_16Siments - Robust Aitchison distance")+
    geom_point(size=4,shape=21,aes(fill=sample_data(ps_Cold_rclr)$Time),color="black")+
    scale_fill_viridis(option="magma",discrete=T,name="Time :")+
    geom_label_npc(data= df.annotations , 
                   aes(npcx = "right", npcy = "bottom", label = label),
                   parse=T,size=6)
RCLR_ord_time_Cold

### Save figure 
RCLR_Cold <- ggarrange(RCLR_ord_plant_Cold,RCLR_ord_time_Cold,
                       labels=c("C","D"),
                       font.label = list(size=17,face="bold"),
                       legend = "bottom")

# ggsave(here("Results_W&C","Figures","water_16S_Cold_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
# ggsave(here("Results_W&C","Figures","water_16S_Cold_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)

##### PW PERMANOVA #####

Pairwise.PT <- pairwise.adonis(rclr_dist_matrix, 
                               metadata$Sample_type,
                               p.adjust.m ="fdr")
Pairwise.PT
# Plant types not significantly different from one another


Pairwise.Time<- pairwise.adonis(rclr_dist_matrix, 
                                metadata$Time,
                                p.adjust.m ="fdr")
Pairwise.Time
# All sampling times are different from one another excet D77 vs D62


####^Common plot ####
RCLR_WC <- ggarrange(RCLR_Warm,RCLR_Cold,
                     nrow=2)
ggsave(here("Results_W&C","Figures","Water_16S_W&C_RCLR_Ordination.pdf"),
       plot=RCLR_WC, device='pdf',height = 7.5, width = 10.5)

ggsave(here("Results_W&C","Figures","Water_16S_W&C_RCLR_Ordination.png"),
       plot=RCLR_WC, device='png',height = 7.5, width = 10.5)

### 



####~~~~~~~~~~~~~~~~####
####~~~~~~~~~~~~~~~~####

#### Not separated by temperature #####
####~~~~~~~~~~~~~~~~####

######## Data ####

load(here("Rdata","ps_16S_water_obj.RData"))
###______#####
### BETA DIV ####

##### Robust Aitchison ####
ps_rclr <- microbiome::transform(ps, "rclr") # Robust Aitchison transformation

## Sanity check ###
# Does it give the same transformation than vegan?
ASV_phylo_rclr <- data.frame(otu_table(ps_rclr))

ASV <- t(data.frame(otu_table(ps))) # Columns as species !
ASV_vegan_rclr <- decostand(x = ASV,method="rclr")
ASV_vegan_rclr <- data.frame(t(ASV_vegan_rclr))# put it back into species as rows

identical(ASV_phylo_rclr,ASV_vegan_rclr) # should be true 

### Permanova 
rclr_dist_matrix <- phyloseq::distance(ps_rclr, method = "euclidean") # Aitchison distance
metadata <- as(sample_data(ps_rclr), "data.frame") # Export data

Permanova.rclr<-adonis2(rclr_dist_matrix~Time*Sample_type*Temperature,
                        data = metadata,
                        permutations = 999)
Permanova.rclr

# Save Permanova resutls in csv file
write.table(Permanova.rclr,row.names=T,sep=";",here("Results","Tables","16S_Water_RCLR_Permanova.csv"))


#### Interactions - Pairwise permanova
metadata$Temperature <- sub("10C day - 5C night","Cold",metadata$Temperature)
metadata$Temperature <- sub("20C day - 10C night","Warm",metadata$Temperature)

metadata$plant_temp = paste0(metadata$Sample_type, "_", metadata$Temperature)
metadata$time_temp = paste0(metadata$Time, "_", metadata$Temperature)
metadata$plant_time = paste0(metadata$Sample_type, "_", metadata$Time)

# Characters to factor
metadata[sapply(metadata, is.character)] <- lapply(metadata[sapply(metadata, is.character)], as.factor) # did it work? Check with str(meta)
str(metadata)

# Plant x Temperature 
Permanova.plant_temp <- adonis2(rclr_dist_matrix~plant_temp,
                                data = metadata, permutations = 999)
Permanova.plant_temp

Pairwise.plant_temp <- pairwise.adonis(rclr_dist_matrix, metadata$plant_temp,p.adjust.m ="bonferroni")
Pairwise.plant_temp
write.table(Pairwise.plant_temp,row.names=T,sep=";",here("Results","Tables","16S_Water_RCLR_PWP_Plant_Temp.csv"))


# Time x Temperature 
Permanova.time_temp <- adonis2(rclr_dist_matrix~time_temp,
                               data = metadata, permutations = 999)
Permanova.time_temp

Pairwise.time_temp <- pairwise.adonis(rclr_dist_matrix, metadata$time_temp,p.adjust.m ="bonferroni")
Pairwise.time_temp
write.table(Pairwise.time_temp,row.names=T,sep=";",here("Results","Tables","16S_Water_RCLR_PWP_Time_Temp.csv"))

# Plant x Time 
Permanova.plant_time <- adonis2(rclr_dist_matrix~plant_time,
                                data = metadata, permutations = 999)
Permanova.plant_time

Pairwise.plant_time <- pairwise.adonis(rclr_dist_matrix, metadata$plant_time,p.adjust.m ="bonferroni")
Pairwise.plant_time
write.table(Pairwise.plant_time,row.names=T,sep=";",here("Results","Tables","16S_Water_RCLR_PWP_Time_Plant.csv"))





#### Ordinations 
ord_rclr <- phyloseq::ordinate(ps_rclr, "RDA", distance = "euclidean")

## Sample type  

summary(sample_data(ps_rclr))

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[2],3))))

RCLR_ord_stype <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Sample_type") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type effect ",subtitle = 'Robust Aitchison distance')+
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  geom_point(aes(shape=sample_data(ps_rclr)$Sample_type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_stype$layers <- RCLR_ord_stype$layers[-1] # removes the original points generated by plot_ordination
RCLR_ord_stype

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[1],3))))

RCLR_ord_time <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Time effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[3],3))))

RCLR_ord_temp <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Temperature effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_rclr)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
RCLR_ord_temp


### Sample type * Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.rclr$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.rclr$`Pr(>F)`[4],3))))

RCLR_ord_STxTime <- phyloseq::plot_ordination(ps_rclr, ord_rclr, type="samples",shape="Sample_type",color="Time") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type * Time effect ",subtitle = 'Robust Aitchison distance')+
  geom_point(size=4,aes(fill=sample_data(ps_rclr)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  scale_color_viridis(option="magma",discrete=T,name="Time")+
  # Add both color and fill to get the desired graphical output
# If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

RCLR_ord_STxTime$layers<- RCLR_ord_STxTime$layers[-1] 
RCLR_ord_STxTime

ggarrange(RCLR_ord_stype,RCLR_ord_temp,RCLR_ord_time,RCLR_ord_STxTime,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","16S_Water_RCLR_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","16S_Water_RCLR_Ordination.png"),device='png',height = 7.5, width = 10.5)
  
#### Pairwise permanova ###
calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Time",999) 
# All sample dates are different from one another

calc_pairwise_permanovas(rclr_dist_matrix, metadata,"Sample_type",999) 
# All sample types are different from one another



#####Hellinger distance #####
### Permanova 
ps_hell <- microbiome::transform(ps, "hellinger")    

hell_dist_matrix <- phyloseq::distance(ps_hell, method = "euclidean") # Hellinger distance
metadata <- as(sample_data(ps_hell), "data.frame") # Export data

Permanova.hell<-adonis2(hell_dist_matrix~Time*Sample_type*Temperature,
                        data = metadata,
                        permutations = 999)
Permanova.hell



write.table(Permanova.hell,row.names=T,sep=";",here("Results","Tables","16S_Water_Hellinger_Permanova.csv"))

## Ordination ##
ord_hell <- phyloseq::ordinate(ps_hell, "RDA", distance = "euclidean")

## Sample type  

# Allows to nicely annotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[2],3))))

Hell_ord_stype <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Sample_type") + 
  theme_bw()+
  ggtitle(label = "Water - sample type effect ",subtitle = 'Hellinger distance')+
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  geom_point(aes(shape=sample_data(ps_hell)$Sample_type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

Hell_ord_stype$layers <- Hell_ord_stype$layers[-1] # removes the original points generated by plot_ordination
Hell_ord_stype

### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[1],3))))

Hell_ord_time <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Time effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
Hell_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[3],3))))

Hell_ord_temp <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Temperature effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps_hell)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
Hell_ord_temp


### Sample type * Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.hell$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.hell$`Pr(>F)`[4],3))))

Hell_ord_STxTime <- phyloseq::plot_ordination(ps_hell, ord_hell, type="samples",shape="Sample_type",color="Time") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type * Time effect ",subtitle = 'Hellinger distance')+
  geom_point(size=4,aes(fill=sample_data(ps_hell)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  scale_color_viridis(option="magma",discrete=T,name="Time")+
  # Add both color and fill to get the desired graphical output
  # If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

Hell_ord_STxTime$layers<- Hell_ord_STxTime$layers[-1] 
Hell_ord_STxTime

ggarrange(Hell_ord_stype,Hell_ord_temp,Hell_ord_time,Hell_ord_STxTime,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","16S_Water_Hell_Ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","16S_Water_Hell_Ordination.png"),device='png',height = 7.5, width = 10.5)




#####Bray_curtis distance #####
### Permanova 

bc_dist_matrix <- phyloseq::distance(ps, method = "bray") # Bray_Curtis distance
metadata <- as(sample_data(ps), "data.frame") # Export data

Permanova.bc<-adonis2(bc_dist_matrix~Time*Sample_type*Temperature,
                        data = metadata,
                        permutations = 999)
Permanova.bc

write.table(Permanova.bc,row.names=T,sep=";",here("Results","Tables","16S_Water_Bray_Curtis_Permanova.csv"))

<<<<<<< HEAD




## PCoA ##
=======
## Ordination ##
>>>>>>> 9ea84a873344d1a08df3b9fea3a79c4857eb9eb6
ord_bc <- phyloseq::ordinate(ps, "PCoA", distance = "bray")


## Sample type  

# Allows to nicely anotate R2 and pvalue with geom_label_npc()
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[2],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[2],3))))

BC_ord_stype <- phyloseq::plot_ordination(ps, ord_bc, type="samples",shape="Sample_type") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type effect ",subtitle = 'Bray_Curtis distance')+
 # geom_text(aes(label = sample_names(ps_root)), size = 3.5)+
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  geom_point(aes(shape=sample_data(ps)$Sample_type),size=4)+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_stype$layers <- BC_ord_stype$layers[-1] # removes the original points generated by plot_ordination
BC_ord_stype


### Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[1],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[1],3))))

BC_ord_time <- phyloseq::plot_ordination(ps, ord_bc, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Time effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps)$Time),color="black")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
BC_ord_time


### Temperature 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[3],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[3],3))))

BC_ord_temp <- phyloseq::plot_ordination(ps, ord_bc, type="samples") + 
  theme_bw()+
  ggtitle(label = "Water - Temperature effect ",subtitle = 'Bray_Curtis distance')+
  geom_point(size=4,shape=21,aes(fill=sample_data(ps)$Temperature),color="black")+
  scale_fill_manual(values=c("#0000FE","#B02223"),name="Temperature")+
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)
BC_ord_temp


### Sample type * Time 
df.annotations <- data.frame(
  label = paste(paste0("~italic(R)^{2} == ", round(Permanova.bc$R2[4],3)),"~~",
                paste0("~italic(p) == ",round(Permanova.bc$`Pr(>F)`[4],3))))

BC_ord_STxTime <- phyloseq::plot_ordination(ps, ord_bc, type="samples",shape="Sample_type",color="Time") + 
  theme_bw()+
  ggtitle(label = "Water - Sample type * Time effect ",subtitle = 'Bray Curtis distance')+
  geom_point(size=4,aes(fill=sample_data(ps)$Time))+
  geom_point(size=4.1,color='black')+ # Workaround to get black outline on previous geom_points 
  scale_shape_manual(values=c(21,22,23),name="Sample type")+
  scale_fill_viridis(option="magma",discrete=T,name="Time")+
  scale_color_viridis(option="magma",discrete=T,name="Time")+
  # Add both color and fill to get the desired graphical output
  # If only fill -> legend is black.. All this because plot_ordination does not have a fill option
  geom_label_npc(data= df.annotations , 
                 aes(npcx = "right", npcy = "bottom", label = label),
                 parse=T,size=4)

BC_ord_STxTime$layers<- BC_ord_STxTime$layers[-1] 
BC_ord_STxTime

ggarrange(BC_ord_stype,BC_ord_temp,BC_ord_time,BC_ord_STxTime,labels="AUTO",legend = "bottom")
ggsave(here("Results","Figures","16S_Water_BC_ordination.pdf"),device='pdf',height = 7.5, width = 10.5)
ggsave(here("Results","Figures","16S_Water_BC_ordination.png"),device='png',height = 7.5, width = 10.5)


